version: 1
disable_existing_loggers: False

formatters:
  pi:
    format: "[%(asctime)s] %(levelname)s [%(channel)s] %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S %Z"
  simple:
    format: "[%(asctime)s] %(levelname)s %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S %Z"

handlers:
  console:
    class: logging.StreamHandler
    formatter: simple
    stream: ext://sys.stdout
  pi-console:
    class: logging.StreamHandler
    formatter: pi
    stream: ext://sys.stdout
  pi-file:
    class: logging.handlers.RotatingFileHandler
    formatter: pi
    filename: /app/logs/app.log
    maxBytes: 10485760
    backupCount: 5
    encoding: utf8

loggers:
  privateindexer:
    handlers: [ pi-console, pi-file ]
    level: INFO
    propagate: False
  uvicorn:
    handlers: [ console ]
    level: WARNING
    propagate: False
  uvicorn.error:
    handlers: [ console ]
    level: WARNING
    propagate: False
  uvicorn.access:
    handlers: [ console ]
    level: WARNING
    propagate: False

root:
  handlers: [ console ]
  level: INFO
